### ISSUE TITLE
.gitignore woes

### ISSUE THREAD

**Issue by stayallive** [felixarntz/site-icon-extended#1]
Hey @felixarntz,

We are using git to keep track of our source and also our plugins, however your `.gitignore` file is causing us some issues when updating this plugin. Since it ignores `vendor/` the plugin breaks when we update it.

Would it be possible to remove the `.gitignore` from the WordPress SVN?

**Comment by felixarntz** [comment]
Hey @Stayallive,

oh I never considered that, thanks for making me aware as that also affects some other plugins I made. I will remove the file today and create a minor release for it.

**Comment by stayallive** [comment]
Thanks @felixarntz! Much appreciated :)
